### ISSUE TITLE
headless issue - undefined 

### ISSUE THREAD

**Issue by Ilovegym66** [foxriver76/ioBroker.puppeteer#12]
Problem only on Bookworm, Raspi 4 and iobroker-Docker Image V9.0.1, no issues with Bookworm in a VM under Proxmox.
Looks like something must be configured for this? 
`
2024-01-09 08:46:08.442  - info: host.iobroker-P4 iobroker add puppeteer auto --host iobroker-P4 --debug
2024-01-09 08:46:12.113  - info: host.iobroker-P4 iobroker NPM version: 10.2.3
2024-01-09 08:46:12.116  - info: host.iobroker-P4 iobroker Installing iobroker.puppeteer@0.2.7... (System call)
2024-01-09 08:46:23.590  - info: host.iobroker-P4 iobroker npm WARN deprecated puppeteer@19.11.1: < 21.3.7 is no longer supported
2024-01-09 08:47:06.792  - info: host.iobroker-P4 iobroker added 71 packages, and removed 4 packages in 54s34 packages are looking for funding  run `npm fund` for details
2024-01-09 08:47:06.927  - info: host.iobroker-P4 iobroker host.iobroker-P4 install adapter puppeteer
2024-01-09 08:50:55.757  - info: host.iobroker-P4 iobroker upload [0] puppeteer.admin /opt/iobroker/node_modules/iobroker.puppeteer/admin/puppeteer.png puppeteer.png image/png
2024-01-09 08:50:55.823  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer created/updated
2024-01-09 08:50:55.883  - info: host.iobroker-P4 iobroker host.iobroker-P4 create instance puppeteer
2024-01-09 08:50:55.899  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.alive created
2024-01-09 08:50:55.924  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.connected created
2024-01-09 08:50:55.945  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.compactMode created
2024-01-09 08:50:55.957  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.cpu created
2024-01-09 08:50:55.968  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.cputime created
2024-01-09 08:50:55.982  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.memHeapUsed created
2024-01-09 08:50:56.003  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.memHeapTotal created
2024-01-09 08:50:56.015  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.memRss created
2024-01-09 08:50:56.028  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.uptime created
2024-01-09 08:50:56.058  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.inputCount created
2024-01-09 08:50:56.069  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.outputCount created
2024-01-09 08:50:56.088  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.eventLoopLag created
2024-01-09 08:50:56.111  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.sigKill created
2024-01-09 08:50:56.122  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0.logLevel created
2024-01-09 08:50:56.133  - info: host.iobroker-P4 iobroker host.iobroker-P4 object puppeteer.0.url created
2024-01-09 08:50:56.145  - info: host.iobroker-P4 iobroker host.iobroker-P4 object puppeteer.0.filename created
2024-01-09 08:50:56.156  - info: host.iobroker-P4 iobroker host.iobroker-P4 object puppeteer.0.fullPage created
2024-01-09 08:50:56.165  - info: host.iobroker-P4 iobroker host.iobroker-P4 object puppeteer.0.clipTop created
2024-01-09 08:50:56.177  - info: host.iobroker-P4 iobroker host.iobroker-P4 object puppeteer.0.clipLeft created
2024-01-09 08:50:56.187  - info: host.iobroker-P4 iobroker host.iobroker-P4 object puppeteer.0.clipWidth created
2024-01-09 08:50:56.198  - info: host.iobroker-P4 iobroker host.iobroker-P4 object puppeteer.0.clipHeight created
2024-01-09 08:50:56.208  - info: host.iobroker-P4 iobroker host.iobroker-P4 object puppeteer.0.renderTime created
2024-01-09 08:50:56.218  - info: host.iobroker-P4 iobroker host.iobroker-P4 object puppeteer.0.waitForSelector created
2024-01-09 08:50:56.227  - info: host.iobroker-P4 iobroker host.iobroker-P4 Set default value of puppeteer.0.fullPage: false
2024-01-09 08:50:56.235  - info: host.iobroker-P4 iobroker host.iobroker-P4 Set default value of puppeteer.0.clipTop: 0
2024-01-09 08:50:56.244  - info: host.iobroker-P4 iobroker host.iobroker-P4 Set default value of puppeteer.0.clipLeft: 0
2024-01-09 08:50:56.259  - info: host.iobroker-P4 iobroker host.iobroker-P4 object system.adapter.puppeteer.0 created
2024-01-09 08:50:57.311  - info: host.iobroker-P4 iobroker exit 0
2024-01-09 08:50:59.299  - info: host.iobroker-P4 instance system.adapter.puppeteer.0 started with pid 131346
2024-01-09 08:51:01.444  - info: puppeteer.0 (131346) starting. Version 0.2.7 in /opt/iobroker/node_modules/iobroker.puppeteer, node: v20.10.0, js-controller: 5.0.17
2024-01-09 08:51:01.533  - error: puppeteer.0 (131346) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 08:51:01.540  - error: puppeteer.0 (131346) unhandled promise rejection: Failed to launch the browser process! undefined
TROUBLESHOOTING: https://pptr.dev/troubleshooting
2024-01-09 08:51:01.542  - error: puppeteer.0 (131346) Error: Failed to launch the browser process! undefined
TROUBLESHOOTING: https://pptr.dev/troubleshooting
    at ChildProcess.onClose (/opt/iobroker/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262:24)
    at ChildProcess.emit (node:events:526:35)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
2024-01-09 08:51:01.544  - error: puppeteer.0 (131346) Failed to launch the browser process! undefined
TROUBLESHOOTING: https://pptr.dev/troubleshooting
2024-01-09 08:51:01.555  - info: puppeteer.0 (131346) terminating
2024-01-09 08:51:01.556  - warn: puppeteer.0 (131346) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-09 08:51:02.060  - info: puppeteer.0 (131346) terminating
2024-01-09 08:51:02.213  - error: host.iobroker-P4 Caught by controller[0]:
2024-01-09 08:51:02.214  - error: host.iobroker-P4 Caught by controller[0]:   Puppeteer old Headless deprecation warning:
2024-01-09 08:51:02.215  - error: host.iobroker-P4 Caught by controller[0]:     In the near feature `headless: true` will default to the new Headless mode
2024-01-09 08:51:02.216  - error: host.iobroker-P4 Caught by controller[0]:     for Chrome instead of the old Headless implementation. For more
2024-01-09 08:51:02.217  - error: host.iobroker-P4 Caught by controller[0]:     information, please see https://developer.chrome.com/articles/new-headless/.
2024-01-09 08:51:02.218  - error: host.iobroker-P4 Caught by controller[0]:     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
2024-01-09 08:51:02.219  - error: host.iobroker-P4 Caught by controller[0]:     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
2024-01-09 08:51:02.220  - error: host.iobroker-P4 instance system.adapter.puppeteer.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-09 08:51:02.221  - info: host.iobroker-P4 Restart adapter system.adapter.puppeteer.0 because enabled
2024-01-09 08:51:32.265  - info: host.iobroker-P4 instance system.adapter.puppeteer.0 started with pid 131600
2024-01-09 08:51:34.341  - info: puppeteer.0 (131600) starting. Version 0.2.7 in /opt/iobroker/node_modules/iobroker.puppeteer, node: v20.10.0, js-controller: 5.0.17
2024-01-09 08:51:34.427  - error: puppeteer.0 (131600) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-09 08:51:34.429  - error: puppeteer.0 (131600) unhandled promise rejection: Failed to launch the browser process! undefined
TROUBLESHOOTING: https://pptr.dev/troubleshooting
2024-01-09 08:51:34.431  - error: puppeteer.0 (131600) Error: Failed to launch the browser process! undefined
TROUBLESHOOTING: https://pptr.dev/troubleshooting
    at ChildProcess.onClose (/opt/iobroker/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262:24)
    at ChildProcess.emit (node:events:526:35)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
2024-01-09 08:51:34.432  - error: puppeteer.0 (131600) Failed to launch the browser process! undefined
TROUBLESHOOTING: https://pptr.dev/troubleshooting
2024-01-09 08:51:34.452  - info: puppeteer.0 (131600) terminating
2024-01-09 08:51:34.454  - warn: puppeteer.0 (131600) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-09 08:51:34.957  - info: puppeteer.0 (131600) terminating
2024-01-09 08:51:35.002  - error: host.iobroker-P4 Caught by controller[0]:
2024-01-09 08:51:35.002  - error: host.iobroker-P4 Caught by controller[0]:   Puppeteer old Headless deprecation warning:
2024-01-09 08:51:35.002  - error: host.iobroker-P4 Caught by controller[0]:     In the near feature `headless: true` will default to the new Headless mode
2024-01-09 08:51:35.003  - error: host.iobroker-P4 Caught by controller[0]:     for Chrome instead of the old Headless implementation. For more
2024-01-09 08:51:35.003  - error: host.iobroker-P4 Caught by controller[0]:     information, please see https://developer.chrome.com/articles/new-headless/.
2024-01-09 08:51:35.003  - error: host.iobroker-P4 Caught by controller[0]:     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
2024-01-09 08:51:35.003  - error: host.iobroker-P4 Caught by controller[0]:     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
2024-01-09 08:51:35.003  - error: host.iobroker-P4 instance system.adapter.puppeteer.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-09 08:51:35.004  - info: host.iobroker-P4 Restart adapter system.adapter.puppeteer.0 because enabled
2024-01-09 08:51:37.718  - info: host.iobroker-P4 "system.adapter.puppeteer.0" disabled
2024-01-09 08:52:06.955  - error: puppeteer.0 (131845) adapter disabled
2024-01-09 08:52:07.011  - warn: puppeteer.0 (131845) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
2024-01-09 08:52:07.568  - error: host.iobroker-P4 instance system.adapter.puppeteer.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
2024-01-09 08:52:07.569  - info: host.iobroker-P4 Do not restart adapter system.adapter.puppeteer.0 because disabled or deleted

`

**Comment by foxriver76** [comment]
I think it is a duplicate of https://github.com/foxriver76/ioBroker.puppeteer/issues/7

**Comment by Ilovegym66** [comment]
yes, can be closed, sorry, double ... now on js-controller 5.0.17 and Node 20.. but this is not problem..
