### ISSUE TITLE
v0.3.0 - command failed at update.. 

### ISSUE THREAD

**Issue by Ilovegym66** [foxriver76/ioBroker.puppeteer#17]
ilovegym@testbroker:/opt/iobroker$ iob update
Used repository: beta
Adapter    "admin"        : 6.17.7   , installed 6.17.3 [Updatable]
Adapter    "javascript"   : 8.3.1    , installed 8.3.0  [Updatable]
Controller "js-controller": 5.0.19   , installed 5.0.19
Adapter    "puppeteer"    : 0.3.0    , installed 0.2.8  [Updatable]
ilovegym@testbroker:/opt/iobroker$ iob upgrade

This upgrade of "puppeteer" will introduce the following changes:
==========================================================================
-> 0.3.0:
allowed to specify additional arguments for the puppeteer process
updated puppeteer dependency
==========================================================================

Would you like to upgrade puppeteer from @0.2.8 to @0.3.0 now? [(y)es, (n)o]: y
Update puppeteer from @0.2.8 to @0.3.0
NPM version: 10.5.0
Installing iobroker.puppeteer@0.3.0... (System call)
npm ERR! code 1
npm ERR! path /opt/iobroker/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.mjs
npm ERR! Error: ERROR: Failed to set up chrome-headless-shell v125.0.6422.60! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR!     at file:///opt/iobroker/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:84:27
npm ERR!     at async Promise.all (index 1)
npm ERR!     at async downloadBrowser (file:///opt/iobroker/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:90:9) {
npm ERR!   [cause]: [Error: ENOSPC: no space left on device, write] {
npm ERR!     errno: -28,
npm ERR!     code: 'ENOSPC',
npm ERR!     syscall: 'write'
npm ERR!   }
npm ERR! }

npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-05-20T07_53_59_180Z-debug-0.log
host.testbroker Cannot install iobroker.puppeteer@0.3.0: 1
ilovegym@testbroker:/opt/iobroker$

Your current setup is:
/usr/bin/nodejs         v18.20.2
/usr/bin/node           v18.20.2
/usr/bin/npm            10.5.0
/usr/bin/npx            10.5.0
/usr/bin/corepack       0.25.2

**Comment by Ilovegym66** [comment]
argh.. no space left on drive.. shit.. sorry. closed.
